approve_by_comment: true
approve_regex: '^([Aa]pprove(d)?|:\+1:|:thumbsup:)'
author_approval: ignored
reject_regex: '^([Rr]eject(ed)?|:-1:|:thumbsdown:)'
reset_on_push: true
reset_on_reopened: true
reviewers:
    -
        name: admins
        teams:
            - admins
        required: 1
        conditions:
            branches:
                - master
    -
        name: reviewers
        teams:
            - reviewers
        required: 1
        conditions:
            branches:
                - master
    -
        name: developers
        teams:
            - developers
        required: 1
        
