sudo: false # use container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

notifications:
  slack:
    rooms:
      - secure: "Bwu4f/O7rdatVpV56wGLNloWJXXCfBf0V9DZLcBl8jbZmqsvwuDVoqItvFMwqmaZU1hx/BWkU1lnWq9OOP+KdcrsmStu4q2RgWzi+DhzTHeFuCog91ekBIt7q2+sYfLVcsUyIo9v0Lajd6sVE0Sn8MDLdVVPER0YIZ24WUndkS/UZb4FfE5xmo9RGHMXtqzTDlwpRCb8RkSQtqT4u15SdVJQnx1rUcD4XUvghdbwGDZD2vLg7ewWT+ubgOPcQ3FzFm9tCldOl5ou75Gz7mt6Gf/QIfK0FiDA0HWD1+RYfw7ipD3Pclr2ZWCTv3tbMdLvA6t0p7HV+r8JH604SpeltgdR1GMcQMG2xva9QYhYg1oZo7+R1DaMiPkWwMaXO2to78WaU5dLvzt6SAv/rLarxaYwAAoo73DEsi65bhmYdTFhKRjdSgZ1l4CfA6ThsYn7Bz4MJPE6h4MtgVc22QHsyLK0IMVg1xAg6aLpPwsKLmjDF8SdrslhD5dRyDoitv1ygwqwXl78GlNArrv7doClzj+PO/e1wdtjyPR9gClib2reVOFT4OftEeqqWD6ffEUTEra9I+U3k4TJjvp5CID/buOZoQaDOcnYYMrxPp7HBoZurb8LPEehyQDSli8wDvHv71HXEa+cYyvc9di8saEwr5zvaqLHjzyKy2aTezAHi2g="
    on_success: change
    on_failure: always

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.gradle/caches' # cache the gradle cache directory
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper directory

before_install:
  - chmod +x gradlew # ensure that the gradlew script is executable

install: true

script:
  - ./gradlew --continue --stacktrace build sonarqube jacocoTestReport coveralls #

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./gradlew bintrayUpload; fi;
