sudo: false # use container-based infrastructure

language: java
jdk:
  - oraclejdk8 # test against version 1.8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.gradle/caches' # cache the gradle cache directory
    - '$HOME/.gradle/wrapper' # cache the gradle wrapper directory

before_install:
  - chmod +x gradlew # make gradlew script executable
  - ./gradlew clean

install:
  - ./gradlew assemble

script:
  - ./gradlew check # perform tests
  - ./gradlew testReport jacocoTestReport # compile test reports

after_success:
  - ./gradlew coveralls #
