# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
server:
  port: 802
---
spring:
  profiles: default
  datasource:
# please set values for the variables (${jdbc.mysql.*}) externally (e.g., environment variables)
    url: jdbc:mysql://${jdbc.mysql.host}:${jdbc.mysql.port}/${jdbc.mysql.schema}
    username: ${jdbc.mysql.username}
    password: ${jdbc.mysql.password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
