# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
server:
  port: 8080
spring:
  datasource:
    initialize: true
    platform: mysql
    url: ${jdbc.url:}
    username: ${jdbc.username:}
    password: ${jdbc.password:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  mail:
    host: smtp-relay.gmail.com
    port: 465
    username: ${gmail.username:}
    password: ${gmail.password:}
    protocol: smtps
    properties:
      starttls:
        enable: true
      auth: true
ncl:
  authentication:
    uri:
      '/authentications': POST # for login
      '/registrations': POST # for apply/join new teams
      '/users/(\w|-)+': GET # for retrieving public teams' owner info
      '/users/(\w|-)+/emails/\w+=*': PUT # for email verifications
      '/teams\?visibility=PUBLIC': GET # for retrieving public teams
      '/teams\?name=(\w| )+': GET # for retrieving teams by name
  domain: dev.ncl.sg
  deterlab:
    adapter:
      ip: test.ncl.sg
      port: 8080
      bossUrl: 172.18.178.10
      userUrl: 172.18.178.11
  jwt:
    api-key: ${jwt.key:}
    signing-algorithm: HS512
    expiry-duration: PT1H
  mail:
    delay: 10_000
deterurl:
  bossurl: 172.18.178.10
  userurl: 172.18.178.11
  port: 80
# temporary hack
security.user.password: password
