# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
spring:
  datasource:
    url: jdbc:mysql://${jdbc.mysql.host}:3306/${jdbc.mysql.schema} # please set your environment variable
    username: ${jdbc.mysql.username} # please set your environment variable
    password: ${jdbc.mysql.password} # please set your environment variable
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
