# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306 # e.g., jdbc:mysql://localhost:3306/prod?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  mail:
    host: smtp-relay.gmail.com
    port: 465
    username: ${gmail.username}
    password: ${gmail.password}
    protocol: smtps
    properties:
      starttls:
        enable: true
      auth: true
flyway:
  # baseline-version: 1.1
  # baseline-on-migrate: true # for cases when the schema is non-empty and there is no metadata table
  schemas: flyway, prod
  url:  ${db.url:} # e.g., jdbc:mysql://localhost:3306?useSSL=false
  user: ${db.user:}
  password: ${db.password:}
ncl:
  authentication:
    uri:
      '/authentications': POST # for login
      '/datasets\?visibility=PUBLIC': GET # for retrieving public datasets
      '/datasets/(\w|-)+\?visibility=PUBLIC': GET # for retrieving a public dataset
      '/datasets/(\w|-)+/resources/(\w|-)+/download\?visibility=PUBLIC': GET # for downloading a public open resource
      '/datasets/categories/(\w|-)+': GET # for retrieving category for public datasets
      '/datasets/licenses/(\w|-)+': GET # for retrieving license for public datasets
      '/datasets/public/users': POST # for saving public download user info
      '/datasets/public/users/(\w|-)+': GET # for retrieving public download user info
      '/images/global': GET # for retrieving list of global images
      '/registrations': POST # for apply/join new teams
      '/users/(\w|-)+': GET # for retrieving public teams' owner info
      '/registrations/users/(\w|-)+/emails/\w+=*': PUT # for email verifications
      '/users/(\w|-)+/studentInfo': PUT # for new student member to reset password, name and phone
      '/teams\?visibility=PUBLIC': GET # for retrieving public teams
      '/teams\?name=(\w|-)+': GET # for retrieving teams by name
      '/credentials/password/resets': POST
      '/credentials/password': PUT
      '/credentials/(\w|-)+/keys': PUT # for student to reset password key after it expires
      '/telemetry/nodes/counts\?type=FREE': GET # for retrieving free nodes count
      '/telemetry/nodes/counts\?type=TOTAL': GET # for retrieving total nodes count
      '/telemetry/nodes/status': GET # for retrieving all nodes' statuses
      '/telemetry/testbed/stats': GET # for retrieving number of logged in users and running experiments
      '/analytics/usage/calendar\?startDate=\d{4}-\d{2}-\d{2}\&endDate=\d{4}-\d{2}-\d{2}': GET # for retrieving nodes usage reservations for calendar
  domain: dev.ncl.sg
  deterlab:
    adapter:
      ip: 172.18.178.5
      port: 8080
      bossUrl: ${deterlab.boss:}
      userUrl: ${deterlab.user:}
      enabled: true
#      add secret
      secret: ${secret}
  jwt:
    api-key: ${jwt.key:}
    signing-algorithm: HS512
    expiry-duration: PT6H
  mail:
    delay: 10_000
  accounting:
    charges: 0.12
  analytics:
    energyDir: home/sio/energylog
    diskUsageFile: mnt/production_logs/diskspace.txt
    diskUsageEmail:
      enabled: false
      schedule: 0 0 12 ? * ?
    diskSpaceThreshold: # diskspace threshold alert (value in G, M or K)
      warning: 20G
      danger: 25G
deterurl:
  bossurl: 172.18.178.10
  userurl: 172.18.178.11
  port: 80
transmission:
    baseDir: mnt/resources # '/mnt/resources'
    subDirs:
        dataDir: data # '<base_dir>/data/<dataset_id>/<file_name>'
