# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
server:
  port: 8080
spring:
  datasource:
    url: ${jdbc.url:} # e.g., jdbc:mysql://localhost:3306/ncl?useSSL=false
    username: ${jdbc.username:}
    password: ${jdbc.password:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  mail:
    host: smtp-relay.gmail.com
    port: 465
    username: ${gmail.username:}
    password: ${gmail.password:}
    protocol: smtps
    properties:
      starttls:
        enable: true
      auth: true
flyway:
  # baseline-version: 1.1
  # baseline-on-migrate: true # for cases when the schema is non-empty and there is no metadata table
  schemas: flyway, prod
  url: ${db.url:} # e.g., jdbc:mysql://localhost:3306?useSSL=false
  user: ${db.user:}
  password: ${db.password:}
ncl:
  authentication:
    uri:
      '/authentications': POST # for login
      '/datasets\?visibility=PUBLIC': GET # for retrieving public datasets
      '/registrations': POST # for apply/join new teams
      '/users/(\w|-)+': GET # for retrieving public teams' owner info
      '/users/(\w|-)+/emails/\w+=*': PUT # for email verifications
      '/teams\?visibility=PUBLIC': GET # for retrieving public teams
      '/teams\?name=(\w|-)+': GET # for retrieving teams by name
      '/credentials/password/resets': POST
      '/credentials/password': PUT
      '/telemetry/nodes/counts\?type=FREE': GET # for retrieving free nodes count
      '/telemetry/nodes/counts\?type=TOTAL': GET # for retrieving total nodes count
  domain: dev.ncl.sg
  deterlab:
    adapter:
      ip: test.ncl.sg
      port: 8080
      bossUrl: ${deterlab.boss:}
      userUrl: ${deterlab.user:}
      enabled: false
  jwt:
    api-key: ${jwt.key:}
    signing-algorithm: HS512
    expiry-duration: PT1H
  mail:
    delay: 10_000
deterurl:
  bossurl: 172.18.178.10
  userurl: 172.18.178.11
  port: 80
transmission:
    baseDir: mnt/resources # '/mnt/resources'
    subDirs:
        dataDir: data # '<base_dir>/data/<dataset_id>/<file_name>'
