# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
spring:
  profiles:
    active: authentication-service
server:
  port: 8080
---
spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
