# Spring Boot Configuration
# For more information, please read http://docs.spring.io/spring-boot/docs/current/reference/html/index.html
spring:
  datasource:
    url: jdbc:h2:mem:datajpa
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format-sql: true
ncl:
  jwt:
    apiKey: 123
    signing-algorithm: HS256
    expiry:
      duration: PT1H
